FROM node:16-alpine

RUN mkdir -p /home/app
RUN chown node:node /home/app

USER node

WORKDIR '/home/app'

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node  . .

CMD ["npm", "run", "start"]
